name: pet
description: Flutter Clean Architecture pet project

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  google_fonts: ^4.0.4
  json_annotation: ^4.8.1
  retrofit: ^4.0.3
  routemaster: ^1.0.1
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.6.2
  retrofit_generator: ^8.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/google_fonts/
